vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        vehicule_images:
            uri_prefix: /vehicule
            upload_destination: '%kernel.project_dir%/public/vehicule'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
